[project]
name="MemoryModelAlmanac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python=">=3.9"
dependencies = [
    "ipykernel>=6.30.1",
]

[dependency-groups]
dev = [
    "nbdev>=2.4.5",
]
