# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MemoryModelAlmanac',
                'doc_host': 'https://hanleyc01.github.io',
                'git_url': 'https://github.com/hanleyc01/MemoryModelAlmanac',
                'lib_path': 'MemoryModelAlmanac'},
  'syms': {'MemoryModelAlmanac.core': {'MemoryModelAlmanac.core.foo': ('core.html#foo', 'MemoryModelAlmanac/core.py')}}}
